// Lab 5.14 - feedforward COARSE carrier-frequency-offset estimate + NCO derotate.
//
// GENERATED by scratchpad/gen_coarse_cfo_rtl.py from the proven model coarse_cfo_ref.py --
// the cos/sin LUT and the CORDIC atan table are embedded identically, so this RTL matches the
// float/fixed model bit for bit. Do not hand-edit the tables; regenerate.
//
// Two boards have independent references, so the received carrier sits tens of kHz off. A
// Costas loop pulls in only a few hundred Hz, so this removes the bulk first, feedforward,
// and hands the Costas a Costas-trackable residual.
//
//   y[n]^4 strips QPSK modulation (a^4 = -1), so d = sum y[n]^4 * conj(y[n-1]^4) = sum e^(j4w)
//   angle(d)/4 = w, the per-symbol phase increment. Unambiguous over +-1/8 cycle/symbol =
//   +-60 kHz at 480 kSym/s. The estimate is formed over WIN_SYMBOLS, a sequential CORDIC takes
//   the angle (once per burst, so 1 iteration/clock is cheap), and a delay line holds the burst
//   so the WHOLE burst is released derotated, delayed by WIN -- nothing is lost.
//
// The squares are right-shifted by SQ_SHIFT after each multiply: magnitude squares each time,
// so the shift ~ log2(|symbol|) keeps the datapath from over/underflowing. Angle is
// scale-invariant, so any shift in a ~4-bit window works; SQ_SHIFT=11 suits the raw
// matched-filter symbols (|sym| ~ 2000) and tolerates roughly |sym| 500..8000 (verified in
// coarse_cfo_ref.py). Signal-present gating (SIG_THRESH, same idea as the Costas freeze gate)
// keeps pre-frame noise out of the estimate.
//
// Pass-through when `enable` is low, so the coherent single-board / fabric paths are untouched.

`timescale 1ns/1ps

module qpsk_coarse_cfo #(
    parameter integer W = 16,
    parameter integer PHASE_W = 24,
    parameter integer WIN_SYMBOLS = 64,
    parameter integer SQ_SHIFT = 11,
    parameter integer SIG_THRESH = 1000,
    parameter integer CORDIC_N = 20,
    parameter integer LUT_AW = 8,
    parameter integer ACC_W = 48,
    parameter integer GUARD = 12               // delay-line slack for the CORDIC latency
) (
    input  wire                 clk,
    input  wire                 rst,
    input  wire                 enable,
    input  wire                 in_valid,
    input  wire signed [W-1:0]  in_i,
    input  wire signed [W-1:0]  in_q,
    output wire                 out_valid,
    output wire signed [W-1:0]  out_i,
    output wire signed [W-1:0]  out_q,
    output wire                 cfo_ready,
    output wire signed [PHASE_W-1:0] cfo_omega  // per-symbol phase increment, for observability
);

localparam integer DEPTH = WIN_SYMBOLS + GUARD;

integer k;

// ---------------------------------------------------------------------------
// embedded tables (identical to coarse_cfo_ref.py)
// ---------------------------------------------------------------------------
reg [31:0] cos_sin [0:255];                       // {cos[15:0], sin[15:0]} Q15
reg signed [PHASE_W+1:0] atant [0:CORDIC_N-1];    // atan(2^-i) in PHASE_W phase units
initial begin
    cos_sin[  0] = 32'h7fff0000;
    cos_sin[  1] = 32'h7ff50324;
    cos_sin[  2] = 32'h7fd80648;
    cos_sin[  3] = 32'h7fa6096a;
    cos_sin[  4] = 32'h7f610c8c;
    cos_sin[  5] = 32'h7f090fab;
    cos_sin[  6] = 32'h7e9c12c8;
    cos_sin[  7] = 32'h7e1d15e2;
    cos_sin[  8] = 32'h7d8918f9;
    cos_sin[  9] = 32'h7ce31c0b;
    cos_sin[ 10] = 32'h7c291f1a;
    cos_sin[ 11] = 32'h7b5c2223;
    cos_sin[ 12] = 32'h7a7c2528;
    cos_sin[ 13] = 32'h79892826;
    cos_sin[ 14] = 32'h78842b1f;
    cos_sin[ 15] = 32'h776b2e11;
    cos_sin[ 16] = 32'h764130fb;
    cos_sin[ 17] = 32'h750433df;
    cos_sin[ 18] = 32'h73b536ba;
    cos_sin[ 19] = 32'h7254398c;
    cos_sin[ 20] = 32'h70e23c56;
    cos_sin[ 21] = 32'h6f5e3f17;
    cos_sin[ 22] = 32'h6dc941ce;
    cos_sin[ 23] = 32'h6c23447a;
    cos_sin[ 24] = 32'h6a6d471c;
    cos_sin[ 25] = 32'h68a649b4;
    cos_sin[ 26] = 32'h66cf4c3f;
    cos_sin[ 27] = 32'h64e84ebf;
    cos_sin[ 28] = 32'h62f15133;
    cos_sin[ 29] = 32'h60eb539b;
    cos_sin[ 30] = 32'h5ed755f5;
    cos_sin[ 31] = 32'h5cb35842;
    cos_sin[ 32] = 32'h5a825a82;
    cos_sin[ 33] = 32'h58425cb3;
    cos_sin[ 34] = 32'h55f55ed7;
    cos_sin[ 35] = 32'h539b60eb;
    cos_sin[ 36] = 32'h513362f1;
    cos_sin[ 37] = 32'h4ebf64e8;
    cos_sin[ 38] = 32'h4c3f66cf;
    cos_sin[ 39] = 32'h49b468a6;
    cos_sin[ 40] = 32'h471c6a6d;
    cos_sin[ 41] = 32'h447a6c23;
    cos_sin[ 42] = 32'h41ce6dc9;
    cos_sin[ 43] = 32'h3f176f5e;
    cos_sin[ 44] = 32'h3c5670e2;
    cos_sin[ 45] = 32'h398c7254;
    cos_sin[ 46] = 32'h36ba73b5;
    cos_sin[ 47] = 32'h33df7504;
    cos_sin[ 48] = 32'h30fb7641;
    cos_sin[ 49] = 32'h2e11776b;
    cos_sin[ 50] = 32'h2b1f7884;
    cos_sin[ 51] = 32'h28267989;
    cos_sin[ 52] = 32'h25287a7c;
    cos_sin[ 53] = 32'h22237b5c;
    cos_sin[ 54] = 32'h1f1a7c29;
    cos_sin[ 55] = 32'h1c0b7ce3;
    cos_sin[ 56] = 32'h18f97d89;
    cos_sin[ 57] = 32'h15e27e1d;
    cos_sin[ 58] = 32'h12c87e9c;
    cos_sin[ 59] = 32'h0fab7f09;
    cos_sin[ 60] = 32'h0c8c7f61;
    cos_sin[ 61] = 32'h096a7fa6;
    cos_sin[ 62] = 32'h06487fd8;
    cos_sin[ 63] = 32'h03247ff5;
    cos_sin[ 64] = 32'h00007fff;
    cos_sin[ 65] = 32'hfcdc7ff5;
    cos_sin[ 66] = 32'hf9b87fd8;
    cos_sin[ 67] = 32'hf6967fa6;
    cos_sin[ 68] = 32'hf3747f61;
    cos_sin[ 69] = 32'hf0557f09;
    cos_sin[ 70] = 32'hed387e9c;
    cos_sin[ 71] = 32'hea1e7e1d;
    cos_sin[ 72] = 32'he7077d89;
    cos_sin[ 73] = 32'he3f57ce3;
    cos_sin[ 74] = 32'he0e67c29;
    cos_sin[ 75] = 32'hdddd7b5c;
    cos_sin[ 76] = 32'hdad87a7c;
    cos_sin[ 77] = 32'hd7da7989;
    cos_sin[ 78] = 32'hd4e17884;
    cos_sin[ 79] = 32'hd1ef776b;
    cos_sin[ 80] = 32'hcf057641;
    cos_sin[ 81] = 32'hcc217504;
    cos_sin[ 82] = 32'hc94673b5;
    cos_sin[ 83] = 32'hc6747254;
    cos_sin[ 84] = 32'hc3aa70e2;
    cos_sin[ 85] = 32'hc0e96f5e;
    cos_sin[ 86] = 32'hbe326dc9;
    cos_sin[ 87] = 32'hbb866c23;
    cos_sin[ 88] = 32'hb8e46a6d;
    cos_sin[ 89] = 32'hb64c68a6;
    cos_sin[ 90] = 32'hb3c166cf;
    cos_sin[ 91] = 32'hb14164e8;
    cos_sin[ 92] = 32'haecd62f1;
    cos_sin[ 93] = 32'hac6560eb;
    cos_sin[ 94] = 32'haa0b5ed7;
    cos_sin[ 95] = 32'ha7be5cb3;
    cos_sin[ 96] = 32'ha57e5a82;
    cos_sin[ 97] = 32'ha34d5842;
    cos_sin[ 98] = 32'ha12955f5;
    cos_sin[ 99] = 32'h9f15539b;
    cos_sin[100] = 32'h9d0f5133;
    cos_sin[101] = 32'h9b184ebf;
    cos_sin[102] = 32'h99314c3f;
    cos_sin[103] = 32'h975a49b4;
    cos_sin[104] = 32'h9593471c;
    cos_sin[105] = 32'h93dd447a;
    cos_sin[106] = 32'h923741ce;
    cos_sin[107] = 32'h90a23f17;
    cos_sin[108] = 32'h8f1e3c56;
    cos_sin[109] = 32'h8dac398c;
    cos_sin[110] = 32'h8c4b36ba;
    cos_sin[111] = 32'h8afc33df;
    cos_sin[112] = 32'h89bf30fb;
    cos_sin[113] = 32'h88952e11;
    cos_sin[114] = 32'h877c2b1f;
    cos_sin[115] = 32'h86772826;
    cos_sin[116] = 32'h85842528;
    cos_sin[117] = 32'h84a42223;
    cos_sin[118] = 32'h83d71f1a;
    cos_sin[119] = 32'h831d1c0b;
    cos_sin[120] = 32'h827718f9;
    cos_sin[121] = 32'h81e315e2;
    cos_sin[122] = 32'h816412c8;
    cos_sin[123] = 32'h80f70fab;
    cos_sin[124] = 32'h809f0c8c;
    cos_sin[125] = 32'h805a096a;
    cos_sin[126] = 32'h80280648;
    cos_sin[127] = 32'h800b0324;
    cos_sin[128] = 32'h80010000;
    cos_sin[129] = 32'h800bfcdc;
    cos_sin[130] = 32'h8028f9b8;
    cos_sin[131] = 32'h805af696;
    cos_sin[132] = 32'h809ff374;
    cos_sin[133] = 32'h80f7f055;
    cos_sin[134] = 32'h8164ed38;
    cos_sin[135] = 32'h81e3ea1e;
    cos_sin[136] = 32'h8277e707;
    cos_sin[137] = 32'h831de3f5;
    cos_sin[138] = 32'h83d7e0e6;
    cos_sin[139] = 32'h84a4dddd;
    cos_sin[140] = 32'h8584dad8;
    cos_sin[141] = 32'h8677d7da;
    cos_sin[142] = 32'h877cd4e1;
    cos_sin[143] = 32'h8895d1ef;
    cos_sin[144] = 32'h89bfcf05;
    cos_sin[145] = 32'h8afccc21;
    cos_sin[146] = 32'h8c4bc946;
    cos_sin[147] = 32'h8dacc674;
    cos_sin[148] = 32'h8f1ec3aa;
    cos_sin[149] = 32'h90a2c0e9;
    cos_sin[150] = 32'h9237be32;
    cos_sin[151] = 32'h93ddbb86;
    cos_sin[152] = 32'h9593b8e4;
    cos_sin[153] = 32'h975ab64c;
    cos_sin[154] = 32'h9931b3c1;
    cos_sin[155] = 32'h9b18b141;
    cos_sin[156] = 32'h9d0faecd;
    cos_sin[157] = 32'h9f15ac65;
    cos_sin[158] = 32'ha129aa0b;
    cos_sin[159] = 32'ha34da7be;
    cos_sin[160] = 32'ha57ea57e;
    cos_sin[161] = 32'ha7bea34d;
    cos_sin[162] = 32'haa0ba129;
    cos_sin[163] = 32'hac659f15;
    cos_sin[164] = 32'haecd9d0f;
    cos_sin[165] = 32'hb1419b18;
    cos_sin[166] = 32'hb3c19931;
    cos_sin[167] = 32'hb64c975a;
    cos_sin[168] = 32'hb8e49593;
    cos_sin[169] = 32'hbb8693dd;
    cos_sin[170] = 32'hbe329237;
    cos_sin[171] = 32'hc0e990a2;
    cos_sin[172] = 32'hc3aa8f1e;
    cos_sin[173] = 32'hc6748dac;
    cos_sin[174] = 32'hc9468c4b;
    cos_sin[175] = 32'hcc218afc;
    cos_sin[176] = 32'hcf0589bf;
    cos_sin[177] = 32'hd1ef8895;
    cos_sin[178] = 32'hd4e1877c;
    cos_sin[179] = 32'hd7da8677;
    cos_sin[180] = 32'hdad88584;
    cos_sin[181] = 32'hdddd84a4;
    cos_sin[182] = 32'he0e683d7;
    cos_sin[183] = 32'he3f5831d;
    cos_sin[184] = 32'he7078277;
    cos_sin[185] = 32'hea1e81e3;
    cos_sin[186] = 32'hed388164;
    cos_sin[187] = 32'hf05580f7;
    cos_sin[188] = 32'hf374809f;
    cos_sin[189] = 32'hf696805a;
    cos_sin[190] = 32'hf9b88028;
    cos_sin[191] = 32'hfcdc800b;
    cos_sin[192] = 32'h00008001;
    cos_sin[193] = 32'h0324800b;
    cos_sin[194] = 32'h06488028;
    cos_sin[195] = 32'h096a805a;
    cos_sin[196] = 32'h0c8c809f;
    cos_sin[197] = 32'h0fab80f7;
    cos_sin[198] = 32'h12c88164;
    cos_sin[199] = 32'h15e281e3;
    cos_sin[200] = 32'h18f98277;
    cos_sin[201] = 32'h1c0b831d;
    cos_sin[202] = 32'h1f1a83d7;
    cos_sin[203] = 32'h222384a4;
    cos_sin[204] = 32'h25288584;
    cos_sin[205] = 32'h28268677;
    cos_sin[206] = 32'h2b1f877c;
    cos_sin[207] = 32'h2e118895;
    cos_sin[208] = 32'h30fb89bf;
    cos_sin[209] = 32'h33df8afc;
    cos_sin[210] = 32'h36ba8c4b;
    cos_sin[211] = 32'h398c8dac;
    cos_sin[212] = 32'h3c568f1e;
    cos_sin[213] = 32'h3f1790a2;
    cos_sin[214] = 32'h41ce9237;
    cos_sin[215] = 32'h447a93dd;
    cos_sin[216] = 32'h471c9593;
    cos_sin[217] = 32'h49b4975a;
    cos_sin[218] = 32'h4c3f9931;
    cos_sin[219] = 32'h4ebf9b18;
    cos_sin[220] = 32'h51339d0f;
    cos_sin[221] = 32'h539b9f15;
    cos_sin[222] = 32'h55f5a129;
    cos_sin[223] = 32'h5842a34d;
    cos_sin[224] = 32'h5a82a57e;
    cos_sin[225] = 32'h5cb3a7be;
    cos_sin[226] = 32'h5ed7aa0b;
    cos_sin[227] = 32'h60ebac65;
    cos_sin[228] = 32'h62f1aecd;
    cos_sin[229] = 32'h64e8b141;
    cos_sin[230] = 32'h66cfb3c1;
    cos_sin[231] = 32'h68a6b64c;
    cos_sin[232] = 32'h6a6db8e4;
    cos_sin[233] = 32'h6c23bb86;
    cos_sin[234] = 32'h6dc9be32;
    cos_sin[235] = 32'h6f5ec0e9;
    cos_sin[236] = 32'h70e2c3aa;
    cos_sin[237] = 32'h7254c674;
    cos_sin[238] = 32'h73b5c946;
    cos_sin[239] = 32'h7504cc21;
    cos_sin[240] = 32'h7641cf05;
    cos_sin[241] = 32'h776bd1ef;
    cos_sin[242] = 32'h7884d4e1;
    cos_sin[243] = 32'h7989d7da;
    cos_sin[244] = 32'h7a7cdad8;
    cos_sin[245] = 32'h7b5cdddd;
    cos_sin[246] = 32'h7c29e0e6;
    cos_sin[247] = 32'h7ce3e3f5;
    cos_sin[248] = 32'h7d89e707;
    cos_sin[249] = 32'h7e1dea1e;
    cos_sin[250] = 32'h7e9ced38;
    cos_sin[251] = 32'h7f09f055;
    cos_sin[252] = 32'h7f61f374;
    cos_sin[253] = 32'h7fa6f696;
    cos_sin[254] = 32'h7fd8f9b8;
    cos_sin[255] = 32'h7ff5fcdc;
    atant[ 0] = 26'sd2097152;
    atant[ 1] = 26'sd1238021;
    atant[ 2] = 26'sd654136;
    atant[ 3] = 26'sd332050;
    atant[ 4] = 26'sd166669;
    atant[ 5] = 26'sd83416;
    atant[ 6] = 26'sd41718;
    atant[ 7] = 26'sd20860;
    atant[ 8] = 26'sd10430;
    atant[ 9] = 26'sd5215;
    atant[10] = 26'sd2608;
    atant[11] = 26'sd1304;
    atant[12] = 26'sd652;
    atant[13] = 26'sd326;
    atant[14] = 26'sd163;
    atant[15] = 26'sd81;
    atant[16] = 26'sd41;
    atant[17] = 26'sd20;
    atant[18] = 26'sd10;
    atant[19] = 26'sd5;
end

// ---------------------------------------------------------------------------
// delay line (indexed by symbol: written on in_valid)
// ---------------------------------------------------------------------------
reg signed [W-1:0] dl_i [0:DEPTH-1];
reg signed [W-1:0] dl_q [0:DEPTH-1];
always @(posedge clk) begin
    if (in_valid) begin
        dl_i[0] <= in_i;
        dl_q[0] <= in_q;
        for (k = 1; k < DEPTH; k = k + 1) begin
            dl_i[k] <= dl_i[k-1];
            dl_q[k] <= dl_q[k-1];
        end
    end
end

// ---------------------------------------------------------------------------
// signal-present gate
// ---------------------------------------------------------------------------
wire [W-1:0] abs_i = in_i[W-1] ? (~in_i + 1'b1) : in_i;
wire [W-1:0] abs_q = in_q[W-1] ? (~in_q + 1'b1) : in_q;
wire [W:0]   mag   = {1'b0, abs_i} + {1'b0, abs_q};
wire sig_present = (SIG_THRESH == 0) || (mag >= SIG_THRESH[W:0]);

// ---------------------------------------------------------------------------
// complex 4th power of the input symbol, PIPELINED into two square stages, each
// registered on in_valid, so no single sample-clock period carries more than one
// 24x24 multiply. A fully combinational in -> y2 -> y4 -> differential-product chain
// is ~14 ns of cascaded DSPs and does not close on the 8 ns divide-select clock; the
// pipeline (and the differential product below) makes every stage a single multiply.
//   y2 = (i*i - q*q, 2*i*q) >> SQ_SHIFT ; y4 = square(y2) >> SQ_SHIFT
// ---------------------------------------------------------------------------
// stage 1: square of the CURRENT input -> registered y2
wire signed [2*W-1:0] ii = in_i * in_i;
wire signed [2*W-1:0] qq = in_q * in_q;
wire signed [2*W-1:0] iq = in_i * in_q;
wire signed [2*W:0]   y2i_f = ii - qq;
wire signed [2*W:0]   y2q_f = (iq <<< 1);
wire signed [W+3:0]   y2i_c = y2i_f >>> SQ_SHIFT;
wire signed [W+3:0]   y2q_c = y2q_f >>> SQ_SHIFT;
reg  signed [W+3:0]   y2i_r, y2q_r;
// stage 2: square of the REGISTERED y2 -> registered y4 (the 4th power)
wire signed [2*(W+4)-1:0] aa = y2i_r * y2i_r;
wire signed [2*(W+4)-1:0] bb = y2q_r * y2q_r;
wire signed [2*(W+4)-1:0] ab = y2i_r * y2q_r;
wire signed [2*(W+4):0]   y4i_f = aa - bb;
wire signed [2*(W+4):0]   y4q_f = (ab <<< 1);
wire signed [W+7:0]   y4i_c = y4i_f >>> SQ_SHIFT;
wire signed [W+7:0]   y4q_c = y4q_f >>> SQ_SHIFT;
reg  signed [W+7:0]   y4i_r, y4q_r;

// ---------------------------------------------------------------------------
// FSM: IDLE -> MEASURE (accumulate WIN differential products) -> CORDIC -> DEROTATE
// ---------------------------------------------------------------------------
localparam [1:0] S_IDLE = 2'd0, S_MEASURE = 2'd1, S_CORDIC = 2'd2, S_DEROTATE = 2'd3;
reg [1:0] state = S_IDLE;

reg signed [W+7:0] y4p_i, y4p_q;       // previous symbol's 4th power (y4 delayed one symbol)
reg [15:0] mcnt;                       // accumulated-product counter
reg [2:0]  fill;                       // pipeline-fill counter: skip the first FILL products, which
                                        // are transients while the two square stages + the product
                                        // register fill; only then is p_i_r a valid differential
                                        // product of two consecutive signal symbols.
reg signed [ACC_W-1:0] acc_i, acc_q;   // differential-product accumulator
reg signed [2*(W+8)-1:0] p_i_r, p_q_r; // registered differential product (last pipeline stage)
localparam integer FILL = 4;

// derotate NCO
reg signed [PHASE_W-1:0] theta;
reg signed [PHASE_W-1:0] omega;
reg ready;

// sequential CORDIC registers
reg signed [ACC_W-1:0] cx, cy;
reg signed [PHASE_W+1:0] cang;
reg [7:0] citer;
reg cfold;

// pi and pi/2 in phase units, PHASE_W+2 wide to match cang. Use these SIGNED localparams bare
// below (cang > HALF, cang <= -HALF, cang +/- QUART) -- never a part-select like HALF[PHASE_W+1:0],
// which Verilog treats as UNSIGNED and turns `cang <= -HALF` into an almost-always-true unsigned
// compare (the wrap picks the wrong branch and omega comes out ~pi/2 too high).
localparam signed [PHASE_W+1:0] HALF = (1 <<< (PHASE_W-1));
localparam signed [PHASE_W+1:0] QUART = (1 <<< (PHASE_W-2));

// differential product of the current (registered) 4th power with the previous symbol's:
// y4 * conj(y4_prev). One multiply-add, registered into p_i_r below (its own pipeline stage).
wire signed [2*(W+8)-1:0] p_i_c = y4i_r * y4p_i + y4q_r * y4p_q;
wire signed [2*(W+8)-1:0] p_q_c = y4q_r * y4p_i - y4i_r * y4p_q;

always @(posedge clk) begin
    if (rst) begin
        state <= S_IDLE; mcnt <= 0; fill <= 3'd0;
        acc_i <= 0; acc_q <= 0; theta <= 0; omega <= 0; ready <= 1'b0;
        citer <= 0; cfold <= 1'b0;
    end else begin
        case (state)
        S_IDLE: begin
            ready <= 1'b0; theta <= 0; mcnt <= 0; acc_i <= 0; acc_q <= 0; fill <= 3'd0;
            if (in_valid && sig_present) begin
                // first signal symbol: prime stage 1 of the 4th-power pipeline, start filling
                y2i_r <= y2i_c; y2q_r <= y2q_c;
                fill <= 3'd1;
                state <= S_MEASURE;
            end
        end
        S_MEASURE: begin
            if (in_valid) begin
                // advance every pipeline stage one symbol: square -> 4th power -> delay -> product
                y2i_r <= y2i_c; y2q_r <= y2q_c;   // stage 1
                y4i_r <= y4i_c; y4q_r <= y4q_c;   // stage 2 (4th power)
                y4p_i <= y4i_r; y4p_q <= y4q_r;   // previous symbol's 4th power
                p_i_r <= p_i_c; p_q_r <= p_q_c;   // stage 3 (differential product)
                if (fill < FILL[2:0]) begin
                    // pipeline still filling -- p_i_r is a transient, do not accumulate it
                    fill <= fill + 3'd1;
                end else begin
                    // stage 4: accumulate the valid product (one add per symbol)
                    acc_i <= acc_i + p_i_r;
                    acc_q <= acc_q + p_q_r;
                    if (mcnt == WIN_SYMBOLS[15:0]) begin
                        // launch the sequential CORDIC on the accumulated vector. Its angle is
                        // 4*omega regardless of the exact window position, so a constant CFO gives
                        // the same estimate the un-pipelined version did.
                        cx <= acc_i; cy <= acc_q; cang <= 0; citer <= 0; cfold <= 1'b1;
                        state <= S_CORDIC;
                    end else begin
                        mcnt <= mcnt + 16'd1;
                    end
                end
            end
        end
        S_CORDIC: begin
            if (cfold) begin
                // quadrant fold so the rotation converges (matches the model)
                cfold <= 1'b0;
                if (cx < 0) begin
                    if (cy >= 0) begin cx <= cy;  cy <= -cx; cang <= cang + QUART; end
                    else         begin cx <= -cy; cy <= cx;  cang <= cang - QUART; end
                end
            end else if (citer < CORDIC_N[7:0]) begin
                if (cy > 0) begin
                    cx <= cx + (cy >>> citer);
                    cy <= cy - (cx >>> citer);
                    cang <= cang + atant[citer];
                end else if (cy < 0) begin
                    cx <= cx - (cy >>> citer);
                    cy <= cy + (cx >>> citer);
                    cang <= cang - atant[citer];
                end
                citer <= citer + 8'd1;
            end else begin
                // angle done: wrap to (-pi,pi], omega = angle/4
                if (cang > HALF)        omega <= (cang - (1 <<< PHASE_W)) >>> 2;
                else if (cang <= -HALF) omega <= (cang + (1 <<< PHASE_W)) >>> 2;
                else                                 omega <= cang >>> 2;
                theta <= 0; ready <= 1'b1;
                state <= S_DEROTATE;
            end
        end
        S_DEROTATE: begin
            if (in_valid) theta <= theta + omega;   // advance per released symbol
        end
        default: state <= S_IDLE;
        endcase
    end
end

// ---------------------------------------------------------------------------
// NCO derotate of the DELAYED (oldest) symbol by -theta, PIPELINED: the phase -> Q15 LUT lookup and
// the complex multiply are split by a register so neither the LUT read nor the four 16x16 products
// carry a whole sample-clock period (theta -> LUT -> multiply -> >>>15 is ~11 ns and does not close
// on the 8 ns divide-select clock; synthesis also hides intermediate registers a name-based
// multicycle cannot reach). Stage 1 registers the cos/sin and the symbol (and the passthrough
// symbol, so both modes have identical latency); stage 2 multiplies into the output register.
// ---------------------------------------------------------------------------
wire signed [PHASE_W-1:0] ntheta = -theta;
wire [LUT_AW-1:0] lut_idx = ntheta[PHASE_W-1 -: LUT_AW];
wire signed [15:0] cos_v = cos_sin[lut_idx][31:16];
wire signed [15:0] sin_v = cos_sin[lut_idx][15:0];
wire signed [W-1:0] old_i = dl_i[DEPTH-1];
wire signed [W-1:0] old_q = dl_q[DEPTH-1];

// stage 1: register the LUT output + the delayed symbol + the passthrough symbol, plus valid/ready
reg signed [15:0]  cos_r, sin_r;
reg signed [W-1:0] old_i_r, old_q_r;     // delayed derotate symbol, aligned with cos_r/sin_r
reg signed [W-1:0] pass_i_r, pass_q_r;   // passthrough symbol, same one-stage delay
reg vld1, rdy1;
always @(posedge clk) begin
    if (rst) begin
        vld1 <= 1'b0; rdy1 <= 1'b0;
    end else begin
        vld1 <= in_valid;
        rdy1 <= ready;
        if (in_valid) begin
            cos_r <= cos_v; sin_r <= sin_v;
            old_i_r <= old_i; old_q_r <= old_q;
            pass_i_r <= in_i; pass_q_r <= in_q;
        end
    end
end

// stage 2: complex multiply of the registered LUT and symbol -> registered output
wire signed [W+16-1:0] r_ic = old_i_r * cos_r;
wire signed [W+16-1:0] r_qs = old_q_r * sin_r;
wire signed [W+16-1:0] r_is = old_i_r * sin_r;
wire signed [W+16-1:0] r_qc = old_q_r * cos_r;
wire signed [W-1:0] rot_i = (r_ic - r_qs) >>> 15;
wire signed [W-1:0] rot_q = (r_is + r_qc) >>> 15;

// Registered output. Capturing on the (delayed) valid keeps out_i_r/out_q_r at symbol cadence so
// their input path is a multicycle, and the strobe is delayed to match. Two clocks of latency in
// BOTH modes (passthrough included); the symbol stream is sparse so a uniform delay is transparent
// -- the coherent loopback still decodes at BER 0 (at a start_offset shifted by the pipeline depth).
reg out_valid_r = 1'b0;
reg signed [W-1:0] out_i_r = 0;
reg signed [W-1:0] out_q_r = 0;
always @(posedge clk) begin
    if (rst) begin
        out_valid_r <= 1'b0;
        out_i_r     <= 0;
        out_q_r     <= 0;
    end else begin
        out_valid_r <= enable ? (vld1 && rdy1) : vld1;
        if (vld1) begin
            out_i_r <= enable ? rot_i : pass_i_r;
            out_q_r <= enable ? rot_q : pass_q_r;
        end
    end
end
assign out_valid = out_valid_r;
assign out_i     = out_i_r;
assign out_q     = out_q_r;
assign cfo_ready = ready;
assign cfo_omega = omega;

endmodule
