function lab_4_4_generate_bpsk_simulink_models()
%LAB_4_4_GENERATE_BPSK_SIMULINK_MODELS Generate reproducible Simulink models.

lab_4_4_prepare_bpsk_simulink_workspace();

thisDir = fileparts(mfilename('fullpath'));
blockDir = fileparts(thisDir);
simDir = fullfile(blockDir, 'simulink');
if exist(simDir, 'dir') ~= 7
    mkdir(simDir);
end

create_fixed_point_chain_model(simDir);
create_ideal_ber_model(simDir);
end

function create_fixed_point_chain_model(simDir)
modelName = 'lab_4_4_bpsk_fixed_point_chain';
modelPath = fullfile(simDir, [modelName '.slx']);
reset_model(modelName, modelPath);

set_param(modelName, ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '1', ...
    'StopTime', 'lab44_fixed_chain_stop_time', ...
    'InitFcn', 'lab_4_4_ensure_bpsk_simulink_workspace;');

add_block('simulink/Sources/From Workspace', [modelName '/TX Input'], ...
    'Position', [40 55 170 95], 'VariableName', 'lab44_tx_upsampled_ts');
add_block('simulink/Signal Attributes/Data Type Conversion', [modelName '/TX Q15'], ...
    'Position', [220 55 360 95], 'OutDataTypeStr', 'fixdt(1,16,15)');
add_block('simulink/Discrete/Discrete FIR Filter', [modelName '/TX RRC FIR'], ...
    'Position', [420 40 610 110], ...
    'Coefficients', 'lab44_rrc_taps_q15.''', ...
    'ProductDataTypeStr', 'fixdt(1,32,30)', ...
    'AccumDataTypeStr', 'fixdt(1,40,30)', ...
    'OutDataTypeStr', 'fixdt(1,40,30)', ...
    'RndMeth', 'Nearest', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Math Operations/Gain', [modelName '/TX Gain'], ...
    'Position', [670 55 790 95], 'Gain', 'lab44_tx_gain');
add_block('simulink/Sinks/To Workspace', [modelName '/TX Shaped Out'], ...
    'Position', [860 55 1000 95], 'VariableName', 'lab44_tx_chain_out', 'SaveFormat', 'Timeseries');

add_block('simulink/Sources/From Workspace', [modelName '/RX Corrected'], ...
    'Position', [40 205 170 245], 'VariableName', 'lab44_rx_corrected_ts');
add_block('simulink/Signal Attributes/Data Type Conversion', [modelName '/RX Q15'], ...
    'Position', [220 205 360 245], 'OutDataTypeStr', 'fixdt(1,16,15)');
add_block('simulink/Discrete/Discrete FIR Filter', [modelName '/RX RRC FIR'], ...
    'Position', [420 190 610 260], ...
    'Coefficients', 'lab44_rrc_taps_q15.''', ...
    'ProductDataTypeStr', 'fixdt(1,32,30)', ...
    'AccumDataTypeStr', 'fixdt(1,40,30)', ...
    'OutDataTypeStr', 'fixdt(1,40,30)', ...
    'RndMeth', 'Nearest', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Sinks/To Workspace', [modelName '/RX Matched Out'], ...
    'Position', [860 205 1000 245], 'VariableName', 'lab44_rx_chain_out', 'SaveFormat', 'Timeseries');

add_line(modelName, 'TX Input/1', 'TX Q15/1');
add_line(modelName, 'TX Q15/1', 'TX RRC FIR/1');
add_line(modelName, 'TX RRC FIR/1', 'TX Gain/1');
add_line(modelName, 'TX Gain/1', 'TX Shaped Out/1');

add_line(modelName, 'RX Corrected/1', 'RX Q15/1');
add_line(modelName, 'RX Q15/1', 'RX RRC FIR/1');
add_line(modelName, 'RX RRC FIR/1', 'RX Matched Out/1');

add_block('simulink/Model-Wide Utilities/Model Info', [modelName '/Model Note'], ...
    'Position', [1040 35 1290 270], ...
    'MaskDisplayString', sprintf('Lab 4.4\\nSimulink fixed-point chain\\nInputs from Block 11 handoff\\nQ1.15 FIR taps'));

save_system(modelName, modelPath);
close_system(modelName, 0);
end

function create_ideal_ber_model(simDir)
modelName = 'lab_4_4_bpsk_ideal_ber_awgn';
modelPath = fullfile(simDir, [modelName '.slx']);
reset_model(modelName, modelPath);

set_param(modelName, ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '1', ...
    'StopTime', 'lab44_ber_stop_time', ...
    'InitFcn', 'lab_4_4_ensure_bpsk_simulink_workspace;');

add_block('simulink/Sources/From Workspace', [modelName '/TX Bits'], ...
    'Position', [40 80 170 120], 'VariableName', 'lab44_ber_bits_ts');
add_block('simulink/Signal Attributes/Data Type Conversion', [modelName '/Bits To Double'], ...
    'Position', [220 80 360 120], 'OutDataTypeStr', 'double');
add_block('simulink/Math Operations/Gain', [modelName '/Map Gain'], ...
    'Position', [420 80 520 120], 'Gain', '-2');
add_block('simulink/Math Operations/Bias', [modelName '/Map Bias'], ...
    'Position', [570 80 670 120], 'Bias', '1');
add_block('simulink/Sources/From Workspace', [modelName '/Gaussian Noise'], ...
    'Position', [420 205 550 245], 'VariableName', 'lab44_ber_noise_ts');
add_block('simulink/Math Operations/Gain', [modelName '/Noise Scale'], ...
    'Position', [610 205 730 245], 'Gain', 'lab44_ber_noise_sigma');
add_block('simulink/Math Operations/Sum', [modelName '/Add AWGN'], ...
    'Position', [760 120 810 200], 'Inputs', '++');
add_block('simulink/Sources/Constant', [modelName '/Zero'], ...
    'Position', [860 215 930 245], 'Value', '0');
add_block('simulink/Logic and Bit Operations/Relational Operator', [modelName '/Decision'], ...
    'Position', [970 140 1100 180], 'Operator', '<');
add_block('simulink/Signal Attributes/Data Type Conversion', [modelName '/Bits Out'], ...
    'Position', [1150 140 1280 180], 'OutDataTypeStr', 'uint8');
add_block('simulink/Sinks/To Workspace', [modelName '/RX Bits Out'], ...
    'Position', [1330 140 1470 180], 'VariableName', 'lab44_ber_rx_bits', 'SaveFormat', 'Timeseries');

add_line(modelName, 'TX Bits/1', 'Bits To Double/1');
add_line(modelName, 'Bits To Double/1', 'Map Gain/1');
add_line(modelName, 'Map Gain/1', 'Map Bias/1');
add_line(modelName, 'Map Bias/1', 'Add AWGN/1');
add_line(modelName, 'Gaussian Noise/1', 'Noise Scale/1');
add_line(modelName, 'Noise Scale/1', 'Add AWGN/2');
add_line(modelName, 'Add AWGN/1', 'Decision/1');
add_line(modelName, 'Zero/1', 'Decision/2');
add_line(modelName, 'Decision/1', 'Bits Out/1');
add_line(modelName, 'Bits Out/1', 'RX Bits Out/1');

add_block('simulink/Model-Wide Utilities/Model Info', [modelName '/Model Note'], ...
    'Position', [1330 25 1590 100], ...
    'MaskDisplayString', sprintf('Ideal BPSK over AWGN\\nUse MATLAB runner for BER vs SNR sweep\\nTheoretical overlay is generated outside Simulink'));

save_system(modelName, modelPath);
close_system(modelName, 0);
end

function reset_model(modelName, modelPath)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist(modelPath, 'file') == 2
    delete(modelPath);
end
new_system(modelName);
end
