#!/usr/bin/env python3
"""Emit qpsk_coarse_cfo.v with the cos/sin LUT and CORDIC atan table embedded from the proven
reference model, so the RTL is bit-identical to coarse_cfo_ref.py by construction."""
import sys
from pathlib import Path
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))  # coarse_cfo_ref.py lives beside this
import coarse_cfo_ref as m

PHASE_W = m.PHASE_W          # 24
N = m._CORDIC_N              # 20
ATAN = m._CORDIC_ATAN
lut_cos = [int(round(32767 * np.cos(2 * np.pi * k / 256))) & 0xFFFF for k in range(256)]
lut_sin = [int(round(32767 * np.sin(2 * np.pi * k / 256))) & 0xFFFF for k in range(256)]

OUT = Path(r"g:/Programs/zynq-sdr-course/blocks/block_05_fpga_hdl_flow/rtl/qpsk_coarse_cfo.v")


def lut_lines():
    out = []
    for k in range(256):
        out.append(f"    cos_sin[{k:3d}] = 32'h{lut_cos[k]:04x}{lut_sin[k]:04x};")
    return "\n".join(out)


def atan_lines():
    out = []
    for i in range(N):
        out.append(f"    atant[{i:2d}] = {PHASE_W+2}'sd{ATAN[i]};")
    return "\n".join(out)


HDR = f"""// Lab 5.14 - feedforward COARSE carrier-frequency-offset estimate + NCO derotate.
//
// GENERATED by scratchpad/gen_coarse_cfo_rtl.py from the proven model coarse_cfo_ref.py --
// the cos/sin LUT and the CORDIC atan table are embedded identically, so this RTL matches the
// float/fixed model bit for bit. Do not hand-edit the tables; regenerate.
//
// Two boards have independent references, so the received carrier sits tens of kHz off. A
// Costas loop pulls in only a few hundred Hz, so this removes the bulk first, feedforward,
// and hands the Costas a Costas-trackable residual.
//
//   y[n]^4 strips QPSK modulation (a^4 = -1), so d = sum y[n]^4 * conj(y[n-1]^4) = sum e^(j4w)
//   angle(d)/4 = w, the per-symbol phase increment. Unambiguous over +-1/8 cycle/symbol =
//   +-60 kHz at 480 kSym/s. The estimate is formed over WIN_SYMBOLS, a sequential CORDIC takes
//   the angle (once per burst, so 1 iteration/clock is cheap), and a delay line holds the burst
//   so the WHOLE burst is released derotated, delayed by WIN -- nothing is lost.
//
// The squares are right-shifted by SQ_SHIFT after each multiply: magnitude squares each time,
// so the shift ~ log2(|symbol|) keeps the datapath from over/underflowing. Angle is
// scale-invariant, so any shift in a ~4-bit window works; SQ_SHIFT=11 suits the raw
// matched-filter symbols (|sym| ~ 2000) and tolerates roughly |sym| 500..8000 (verified in
// coarse_cfo_ref.py). Signal-present gating (SIG_THRESH, same idea as the Costas freeze gate)
// keeps pre-frame noise out of the estimate.
//
// Pass-through when `enable` is low, so the coherent single-board / fabric paths are untouched.

`timescale 1ns/1ps

module qpsk_coarse_cfo #(
    parameter integer W = 16,
    parameter integer PHASE_W = {PHASE_W},
    parameter integer WIN_SYMBOLS = 64,
    parameter integer SQ_SHIFT = 11,
    parameter integer SIG_THRESH = 1000,
    parameter integer CORDIC_N = {N},
    parameter integer LUT_AW = 8,
    parameter integer ACC_W = 48,
    parameter integer GUARD = 8               // delay-line slack for the CORDIC latency
) (
    input  wire                 clk,
    input  wire                 rst,
    input  wire                 enable,
    input  wire                 in_valid,
    input  wire signed [W-1:0]  in_i,
    input  wire signed [W-1:0]  in_q,
    output wire                 out_valid,
    output wire signed [W-1:0]  out_i,
    output wire signed [W-1:0]  out_q,
    output wire                 cfo_ready,
    output wire signed [PHASE_W-1:0] cfo_omega  // per-symbol phase increment, for observability
);

localparam integer DEPTH = WIN_SYMBOLS + GUARD;

integer k;

// ---------------------------------------------------------------------------
// embedded tables (identical to coarse_cfo_ref.py)
// ---------------------------------------------------------------------------
reg [31:0] cos_sin [0:255];                       // {{cos[15:0], sin[15:0]}} Q15
reg signed [PHASE_W+1:0] atant [0:CORDIC_N-1];    // atan(2^-i) in PHASE_W phase units
initial begin
{lut_lines()}
{atan_lines()}
end

// ---------------------------------------------------------------------------
// delay line (indexed by symbol: written on in_valid)
// ---------------------------------------------------------------------------
reg signed [W-1:0] dl_i [0:DEPTH-1];
reg signed [W-1:0] dl_q [0:DEPTH-1];
always @(posedge clk) begin
    if (in_valid) begin
        dl_i[0] <= in_i;
        dl_q[0] <= in_q;
        for (k = 1; k < DEPTH; k = k + 1) begin
            dl_i[k] <= dl_i[k-1];
            dl_q[k] <= dl_q[k-1];
        end
    end
end

// ---------------------------------------------------------------------------
// signal-present gate
// ---------------------------------------------------------------------------
wire [W-1:0] abs_i = in_i[W-1] ? (~in_i + 1'b1) : in_i;
wire [W-1:0] abs_q = in_q[W-1] ? (~in_q + 1'b1) : in_q;
wire [W:0]   mag   = {{1'b0, abs_i}} + {{1'b0, abs_q}};
wire sig_present = (SIG_THRESH == 0) || (mag >= SIG_THRESH[W:0]);

// ---------------------------------------------------------------------------
// complex 4th power of the CURRENT input symbol (combinational)
//   y2 = (i*i - q*q, 2*i*q) >> SQ_SHIFT ; y4 = square(y2) >> SQ_SHIFT
// ---------------------------------------------------------------------------
wire signed [2*W-1:0] ii = in_i * in_i;
wire signed [2*W-1:0] qq = in_q * in_q;
wire signed [2*W-1:0] iq = in_i * in_q;
wire signed [2*W:0]   y2i_f = ii - qq;
wire signed [2*W:0]   y2q_f = (iq <<< 1);
wire signed [W+3:0]   y2i = y2i_f >>> SQ_SHIFT;
wire signed [W+3:0]   y2q = y2q_f >>> SQ_SHIFT;
wire signed [2*(W+4)-1:0] aa = y2i * y2i;
wire signed [2*(W+4)-1:0] bb = y2q * y2q;
wire signed [2*(W+4)-1:0] ab = y2i * y2q;
wire signed [2*(W+4):0]   y4i_f = aa - bb;
wire signed [2*(W+4):0]   y4q_f = (ab <<< 1);
wire signed [W+7:0] y4i = y4i_f >>> SQ_SHIFT;
wire signed [W+7:0] y4q = y4q_f >>> SQ_SHIFT;

// ---------------------------------------------------------------------------
// FSM: IDLE -> MEASURE (accumulate WIN differential products) -> CORDIC -> DEROTATE
// ---------------------------------------------------------------------------
localparam [1:0] S_IDLE = 2'd0, S_MEASURE = 2'd1, S_CORDIC = 2'd2, S_DEROTATE = 2'd3;
reg [1:0] state = S_IDLE;

reg signed [W+7:0] y4p_i, y4p_q;       // previous symbol's y4
reg have_prev;
reg [15:0] mcnt;                       // measured-symbol counter
reg signed [ACC_W-1:0] acc_i, acc_q;   // differential-product accumulator

// derotate NCO
reg signed [PHASE_W-1:0] theta;
reg signed [PHASE_W-1:0] omega;
reg ready;

// sequential CORDIC registers
reg signed [ACC_W-1:0] cx, cy;
reg signed [PHASE_W+1:0] cang;
reg [7:0] citer;
reg cfold;

localparam signed [PHASE_W+1:0] HALF = (1 <<< (PHASE_W-1));      // pi (PHASE_W+2 wide to match cang)
localparam signed [PHASE_W+1:0] QUART = (1 <<< (PHASE_W-2));     // pi/2 (PHASE_W+2 wide to match cang)

// differential product of current y4 with previous: y4 * conj(y4_prev)
wire signed [2*(W+8)-1:0] p_i = y4i * y4p_i + y4q * y4p_q;
wire signed [2*(W+8)-1:0] p_q = y4q * y4p_i - y4i * y4p_q;

always @(posedge clk) begin
    if (rst) begin
        state <= S_IDLE; have_prev <= 1'b0; mcnt <= 0;
        acc_i <= 0; acc_q <= 0; theta <= 0; omega <= 0; ready <= 1'b0;
        citer <= 0; cfold <= 1'b0;
    end else begin
        case (state)
        S_IDLE: begin
            ready <= 1'b0; theta <= 0; have_prev <= 1'b0; mcnt <= 0; acc_i <= 0; acc_q <= 0;
            if (in_valid && sig_present) begin
                // first signal symbol: seed prev, start measuring
                y4p_i <= y4i; y4p_q <= y4q; have_prev <= 1'b1; mcnt <= 16'd1;
                state <= S_MEASURE;
            end
        end
        S_MEASURE: begin
            if (in_valid) begin
                if (have_prev) begin
                    acc_i <= acc_i + p_i;
                    acc_q <= acc_q + p_q;
                end
                y4p_i <= y4i; y4p_q <= y4q; have_prev <= 1'b1;
                if (mcnt == WIN_SYMBOLS[15:0]) begin
                    // launch sequential CORDIC on the accumulated vector
                    cx <= acc_i; cy <= acc_q; cang <= 0; citer <= 0; cfold <= 1'b1;
                    state <= S_CORDIC;
                end else begin
                    mcnt <= mcnt + 16'd1;
                end
            end
        end
        S_CORDIC: begin
            if (cfold) begin
                // quadrant fold so the rotation converges (matches the model)
                cfold <= 1'b0;
                if (cx < 0) begin
                    if (cy >= 0) begin cx <= cy;  cy <= -cx; cang <= cang + QUART[PHASE_W+1:0]; end
                    else         begin cx <= -cy; cy <= cx;  cang <= cang - QUART[PHASE_W+1:0]; end
                end
            end else if (citer < CORDIC_N[7:0]) begin
                if (cy > 0) begin
                    cx <= cx + (cy >>> citer);
                    cy <= cy - (cx >>> citer);
                    cang <= cang + atant[citer];
                end else if (cy < 0) begin
                    cx <= cx - (cy >>> citer);
                    cy <= cy + (cx >>> citer);
                    cang <= cang - atant[citer];
                end
                citer <= citer + 8'd1;
            end else begin
                // angle done: wrap to (-pi,pi], omega = angle/4
                if (cang > HALF[PHASE_W+1:0])        omega <= (cang - (1 <<< PHASE_W)) >>> 2;
                else if (cang <= -HALF[PHASE_W+1:0]) omega <= (cang + (1 <<< PHASE_W)) >>> 2;
                else                                 omega <= cang >>> 2;
                theta <= 0; ready <= 1'b1;
                state <= S_DEROTATE;
            end
        end
        S_DEROTATE: begin
            if (in_valid) theta <= theta + omega;   // advance per released symbol
        end
        default: state <= S_IDLE;
        endcase
    end
end

// ---------------------------------------------------------------------------
// NCO derotate of the DELAYED (oldest) symbol by -theta, using the Q15 LUT
// ---------------------------------------------------------------------------
wire signed [PHASE_W-1:0] ntheta = -theta;
wire [LUT_AW-1:0] lut_idx = ntheta[PHASE_W-1 -: LUT_AW];
wire signed [15:0] cos_v = cos_sin[lut_idx][31:16];
wire signed [15:0] sin_v = cos_sin[lut_idx][15:0];
wire signed [W-1:0] old_i = dl_i[DEPTH-1];
wire signed [W-1:0] old_q = dl_q[DEPTH-1];
wire signed [W+16-1:0] r_ic = old_i * cos_v;
wire signed [W+16-1:0] r_qs = old_q * sin_v;
wire signed [W+16-1:0] r_is = old_i * sin_v;
wire signed [W+16-1:0] r_qc = old_q * cos_v;
wire signed [W-1:0] rot_i = (r_ic - r_qs) >>> 15;
wire signed [W-1:0] rot_q = (r_is + r_qc) >>> 15;

// Registered output pipeline. The derotate above (theta -> LUT -> complex multiply -> >>>15) is a
// long combinational path; driving it straight into the downstream Costas per-symbol enable gate
// (loop_run = |in_i|+|in_q| >= SIG_THRESH, which feeds acq_cnt/theta CE) forms a single-cycle
// cross-module path that will not close on the fast divide-select clock. Capture the released
// symbol on in_valid so out_i_r/out_q_r change only at symbol cadence (their input path is then a
// multicycle -- see course_overlay_timing.xdc), and delay the valid strobe by the matching one
// clock so data and valid stay aligned. This adds one clock of latency in BOTH modes (passthrough
// included); the symbol stream is sparse, so a uniform one-clock delay preserves alignment and the
// coherent loopback still decodes at BER 0 (at a start_offset shifted by one).
reg out_valid_r = 1'b0;
reg signed [W-1:0] out_i_r = 0;
reg signed [W-1:0] out_q_r = 0;
always @(posedge clk) begin
    if (rst) begin
        out_valid_r <= 1'b0;
        out_i_r     <= 0;
        out_q_r     <= 0;
    end else begin
        out_valid_r <= enable ? (in_valid && ready) : in_valid;
        if (in_valid) begin
            out_i_r <= enable ? rot_i : in_i;
            out_q_r <= enable ? rot_q : in_q;
        end
    end
end
assign out_valid = out_valid_r;
assign out_i     = out_i_r;
assign out_q     = out_q_r;
assign cfo_ready = ready;
assign cfo_omega = omega;

endmodule
"""

OUT.write_text(HDR, encoding="utf-8")
print(f"wrote {OUT}  ({len(HDR.splitlines())} lines)")
