function end_to_end_bpsk_reference()
%END_TO_END_BPSK_REFERENCE Mirror the Python BPSK reference package in MATLAB.
%
% This script consumes the shared files generated by
% python/end_to_end_bpsk_reference.py and reproduces the key receiver checks:
% waveform rebuild, matched filtering, symbol recovery and BER.

this_dir = fileparts(mfilename('fullpath'));
block_dir = fileparts(this_dir);
blocks_dir = fileparts(block_dir);
repo_root = fileparts(blocks_dir);

package_dir = fullfile(block_dir, 'assets', 'end_to_end_bpsk_reference');
docs_asset_dir = fullfile(repo_root, 'docs', 'assets');

cfg = jsondecode(fileread(fullfile(package_dir, 'config.json')));
bits = load(fullfile(package_dir, 'tx_bits.txt'));
symbol_pairs_q15 = load(fullfile(package_dir, 'tx_symbols_q15.txt'));
taps_q15 = load(fullfile(package_dir, 'rrc_taps_q15.txt'));
sample_plan = jsondecode(fileread(fullfile(package_dir, 'sample_plan.json')));

symbols = double(symbol_pairs_q15(:, 1)) / 32767.0;
taps = double(taps_q15(:)) / 32767.0;
bits = uint8(bits(:));

upsampled = complex(zeros(numel(symbols) * cfg.samples_per_symbol, 1));
upsampled(1:cfg.samples_per_symbol:end) = symbols;
tx_shaped = conv(upsampled, taps);
tx_shaped = tx_shaped .* (cfg.tx_amplitude / max(abs(tx_shaped)));

tx_capture = [
    complex(zeros(cfg.leading_silence_samples, 1));
    tx_shaped;
    complex(zeros(cfg.trailing_silence_samples, 1));
];

tx_reference = read_ci16(fullfile(package_dir, sprintf('%s_tx_reference.ci16', cfg.dataset_id)));
rx_capture = read_ci16(fullfile(package_dir, sprintf('%s.ci16', cfg.dataset_id)));

tx_rmse = sqrt(mean(abs(tx_capture - tx_reference) .^ 2));

n = (0:numel(rx_capture) - 1).';
t = double(n) ./ double(cfg.sample_rate_hz);
rx_corrected = rx_capture .* exp(-1j .* (2.0 .* pi .* cfg.cfo_hz .* t + cfg.phase_offset_rad));
matched = conv(rx_corrected, taps);

sample_start = sample_plan.matched_filter_sample_start + 1;
sample_stop = sample_start + (numel(symbols) - 1) * cfg.samples_per_symbol;
rx_symbols = matched(sample_start:cfg.samples_per_symbol:sample_stop);

gain = (symbols' * rx_symbols) / max(symbols' * symbols, eps);
rx_aligned = rx_symbols ./ gain;
decisions = uint8(real(rx_aligned) < 0);

total_errors = sum(decisions ~= bits);
preamble_count = numel(cfg.preamble_bits);
payload_errors = sum(decisions(preamble_count + 1:end) ~= bits(preamble_count + 1:end));
evm = 100.0 .* sqrt(mean(abs(rx_aligned - symbols) .^ 2)) ./ max(sqrt(mean(abs(symbols) .^ 2)), eps);

summary = struct( ...
    'dataset_id', cfg.dataset_id, ...
    'tx_reference_rmse', tx_rmse, ...
    'bit_errors_total', total_errors, ...
    'bit_errors_payload', payload_errors, ...
    'ber_total', double(total_errors) / max(numel(bits), 1), ...
    'ber_payload', double(payload_errors) / max(double(cfg.payload_bit_count), 1), ...
    'evm_percent', evm ...
);

out_path = fullfile(package_dir, 'matlab_reference_summary.json');
fid = fopen(out_path, 'w');
fwrite(fid, jsonencode(summary, PrettyPrint=true), 'char');
fclose(fid);

fprintf('BPSK MATLAB mirror complete.\n');
fprintf('TX RMSE against exported CI16 reference: %.6e\n', tx_rmse);
fprintf('Total BER: %.6e\n', summary.ber_total);
fprintf('Payload BER: %.6e\n', summary.ber_payload);
fprintf('EVM: %.3f %%\n', summary.evm_percent);

if exist(docs_asset_dir, 'dir') ~= 7
    mkdir(docs_asset_dir);
end
end

function x = read_ci16(path)
fid = fopen(path, 'rb');
if fid < 0
    error('Cannot open %s', path);
end
raw = fread(fid, inf, 'int16=>double');
fclose(fid);

if mod(numel(raw), 2) ~= 0
    error('Invalid CI16 sample count in %s', path);
end

i = raw(1:2:end) ./ 32768.0;
q = raw(2:2:end) ./ 32768.0;
x = complex(i, q);
end
