// Lab 5.6 - self-checking testbench for bpsk_symbol_mapper
//
// Reads vectors generated by python/generate_bpsk_symbol_mapper_vectors.py and
// verifies the RTL output sample-by-sample.

`timescale 1ns/1ps

module tb_bpsk_symbol_mapper;

localparam integer W = 16;
localparam integer NUM_VECTORS = 32;
localparam integer CLK_PERIOD_NS = 10;

reg clk = 1'b0;
reg rst = 1'b1;
reg in_valid = 1'b0;
reg in_bit = 1'b0;

wire out_valid;
wire signed [W-1:0] out_i;
wire signed [W-1:0] out_q;

reg vector_valid [0:NUM_VECTORS-1];
reg vector_bit [0:NUM_VECTORS-1];

reg expected_valid [0:NUM_VECTORS-1];
reg signed [W-1:0] expected_i [0:NUM_VECTORS-1];
reg signed [W-1:0] expected_q [0:NUM_VECTORS-1];

reg expected_valid_current = 1'b0;
reg signed [W-1:0] expected_i_current = 0;
reg signed [W-1:0] expected_q_current = 0;

reg expected_valid_d1 = 1'b0;
reg signed [W-1:0] expected_i_d1 = 0;
reg signed [W-1:0] expected_q_d1 = 0;

integer idx;
integer errors = 0;
integer input_fd;
integer expected_fd;
integer scan_count;
integer tmp_valid;
integer tmp_bit;
integer tmp_i;
integer tmp_q;
reg [1023:0] line;

bpsk_symbol_mapper #(
    .W(W)
) dut (
    .clk(clk),
    .rst(rst),
    .in_valid(in_valid),
    .in_bit(in_bit),
    .out_valid(out_valid),
    .out_i(out_i),
    .out_q(out_q)
);

always #(CLK_PERIOD_NS/2) clk = ~clk;

task read_vectors;
    input [1023:0] input_path;
    input [1023:0] expected_path;
    begin
        input_fd = $fopen(input_path, "r");
        if (input_fd == 0) begin
            $display("ERROR: cannot open input vector file");
            $fatal(1);
        end
        expected_fd = $fopen(expected_path, "r");
        if (expected_fd == 0) begin
            $display("ERROR: cannot open expected vector file");
            $fatal(1);
        end

        scan_count = $fgets(line, input_fd);
        scan_count = $fgets(line, expected_fd);

        for (idx = 0; idx < NUM_VECTORS; idx = idx + 1) begin
            scan_count = $fscanf(input_fd, "%d %d\n", tmp_valid, tmp_bit);
            if (scan_count != 2) begin
                $display("ERROR: failed to read input vector %0d", idx);
                $fatal(1);
            end
            vector_valid[idx] = tmp_valid[0];
            vector_bit[idx] = tmp_bit[0];

            scan_count = $fscanf(expected_fd, "%d %d %d\n", tmp_valid, tmp_i, tmp_q);
            if (scan_count != 3) begin
                $display("ERROR: failed to read expected vector %0d", idx);
                $fatal(1);
            end
            expected_valid[idx] = tmp_valid[0];
            expected_i[idx] = tmp_i[W-1:0];
            expected_q[idx] = tmp_q[W-1:0];
        end

        $fclose(input_fd);
        $fclose(expected_fd);
    end
endtask

initial begin
    read_vectors(
        "blocks/block_05_fpga_hdl_flow/tb/bpsk_symbol_mapper_input_vectors.txt",
        "blocks/block_05_fpga_hdl_flow/tb/bpsk_symbol_mapper_expected_vectors.txt"
    );
end

initial begin
    $dumpfile("blocks/block_05_fpga_hdl_flow/tb/tb_bpsk_symbol_mapper.vcd");
    $dumpvars(0, tb_bpsk_symbol_mapper);

    repeat (3) @(posedge clk);
    @(negedge clk);
    rst = 1'b0;

    for (idx = 0; idx < NUM_VECTORS; idx = idx + 1) begin
        @(negedge clk);
        in_valid = vector_valid[idx];
        in_bit = vector_bit[idx];
        expected_valid_current = expected_valid[idx];
        expected_i_current = expected_i[idx];
        expected_q_current = expected_q[idx];
    end

    @(negedge clk);
    in_valid = 1'b0;
    in_bit = 1'b0;
    expected_valid_current = 1'b0;
    expected_i_current = 0;
    expected_q_current = 0;

    repeat (4) @(posedge clk);

    if (errors == 0) begin
        $display("PASS: bpsk_symbol_mapper test completed without errors");
        $finish;
    end else begin
        $display("FAIL: bpsk_symbol_mapper test completed with %0d errors", errors);
        $fatal(1);
    end
end

always @(posedge clk) begin
    if (rst) begin
        expected_valid_d1 <= 1'b0;
        expected_i_d1 <= 0;
        expected_q_d1 <= 0;
    end else begin
        if (out_valid !== expected_valid_d1) begin
            $display("ERROR at %0t: out_valid=%0b expected=%0b", $time, out_valid, expected_valid_d1);
            errors = errors + 1;
        end

        if (expected_valid_d1) begin
            if (out_i !== expected_i_d1 || out_q !== expected_q_d1) begin
                $display("ERROR at %0t: out=(%0d,%0d) expected=(%0d,%0d)",
                         $time, out_i, out_q, expected_i_d1, expected_q_d1);
                errors = errors + 1;
            end
        end

        expected_valid_d1 <= expected_valid_current;
        expected_i_d1 <= expected_i_current;
        expected_q_d1 <= expected_q_current;
    end
end

endmodule
