`timescale 1ns/1ps

// Bit-exact check of ofdm_cfo_corrector.v against
// verification/vectors/block08_ofdm_cfo_vectors.txt (generated by
// tools/generate_ofdm_cfo_vectors.py from the fixed-point model). The block is
// reset before every stream; samples enter with random gaps and the output sees
// random backpressure. Every output sample must match in value and order,
// out_last must mark the 80th sample of each symbol, frame_error must stay 0.
module tb_ofdm_cfo_corrector;
    localparam VECTORS = "verification/vectors/block08_ofdm_cfo_vectors.txt";
    localparam integer MAX_LINES = 4096;

    reg clk = 1'b0;
    always #5 clk = ~clk;

    reg resetn = 1'b0;
    reg in_valid = 1'b0;
    wire in_ready;
    reg signed [15:0] in_re = 16'sd0;
    reg signed [15:0] in_im = 16'sd0;
    reg in_last = 1'b0;
    wire out_valid;
    reg out_ready = 1'b1;
    wire signed [15:0] out_re;
    wire signed [15:0] out_im;
    wire out_last;
    wire signed [23:0] theta;
    wire [15:0] symbol_count;
    wire frame_error;

    ofdm_cfo_corrector dut (
        .clk(clk), .resetn(resetn), .restart(1'b0),
        .in_valid(in_valid), .in_ready(in_ready), .in_re(in_re), .in_im(in_im), .in_last(in_last),
        .out_valid(out_valid), .out_ready(out_ready), .out_re(out_re), .out_im(out_im), .out_last(out_last),
        .theta(theta), .symbol_count(symbol_count), .frame_error(frame_error)
    );

    integer v_stream [0:MAX_LINES-1];
    integer v_sample [0:MAX_LINES-1];
    integer v_xr [0:MAX_LINES-1];
    integer v_xi [0:MAX_LINES-1];
    integer v_yr [0:MAX_LINES-1];
    integer v_yi [0:MAX_LINES-1];
    integer n_lines = 0;
    integer fd, scanned, s, f, k, xr, xi, yr, yi;
    integer errors = 0;
    integer checked = 0;
    integer seed = 32'hCF0C;
    integer first, last_line, line, expect_ptr, streams_done, timeout;

    always @(posedge clk) begin
        if (resetn && out_valid && out_ready) begin
            if (expect_ptr >= last_line) begin
                $display("FAIL unexpected output sample");
                errors = errors + 1;
            end else begin
                if ($signed(out_re) !== v_yr[expect_ptr] || $signed(out_im) !== v_yi[expect_ptr] ||
                    out_last !== (v_sample[expect_ptr] == 79)) begin
                    if (errors < 8)
                        $display("FAIL stream %0d line %0d sample %0d: got (%0d,%0d) last %0d, expected (%0d,%0d)",
                                 v_stream[expect_ptr], expect_ptr, v_sample[expect_ptr], out_re, out_im, out_last,
                                 v_yr[expect_ptr], v_yi[expect_ptr]);
                    errors = errors + 1;
                end
                checked = checked + 1;
                expect_ptr = expect_ptr + 1;
            end
        end
    end

    always @(negedge clk)
        out_ready <= ($random(seed) & 3) != 0;

    initial begin
        fd = $fopen(VECTORS, "r");
        if (fd == 0) begin
            $display("FAIL cannot open the vector file");
            $fatal(1);
        end
        while (!$feof(fd)) begin
            scanned = $fscanf(fd, "%d %d %d %d %d %d %d\n", s, f, k, xr, xi, yr, yi);
            if (scanned == 7) begin
                v_stream[n_lines] = s; v_sample[n_lines] = k;
                v_xr[n_lines] = xr; v_xi[n_lines] = xi; v_yr[n_lines] = yr; v_yi[n_lines] = yi;
                n_lines = n_lines + 1;
            end
        end
        $fclose(fd);

        streams_done = 0;
        first = 0;
        while (first < n_lines) begin
            last_line = first;
            while (last_line < n_lines && v_stream[last_line] == v_stream[first])
                last_line = last_line + 1;
            expect_ptr = first;

            resetn = 1'b0;
            repeat (3) @(posedge clk);
            @(negedge clk);
            resetn = 1'b1;

            for (line = first; line < last_line; line = line + 1) begin
                @(negedge clk);
                while (($random(seed) & 3) == 0) begin
                    in_valid = 1'b0;
                    @(negedge clk);
                end
                in_valid = 1'b1;
                in_re = v_xr[line];
                in_im = v_xi[line];
                in_last = (v_sample[line] == 79);
                @(posedge clk);
                while (!in_ready)
                    @(posedge clk);
            end
            @(negedge clk);
            in_valid = 1'b0;
            timeout = 0;
            while (expect_ptr < last_line && timeout < 5000) begin
                @(posedge clk);
                timeout = timeout + 1;
            end
            if (expect_ptr != last_line) begin
                $display("FAIL stream %0d: %0d samples missing", v_stream[first], last_line - expect_ptr);
                errors = errors + 1;
            end
            if (frame_error) begin
                $display("FAIL stream %0d: frame_error set", v_stream[first]);
                errors = errors + 1;
            end
            streams_done = streams_done + 1;
            first = last_line;
        end

        // A misplaced in_last (on the 10th sample) must set frame_error.
        resetn = 1'b0;
        repeat (3) @(posedge clk);
        @(negedge clk);
        resetn = 1'b1;
        expect_ptr = 0;
        last_line = 0;
        for (line = 0; line < 10; line = line + 1) begin
            @(negedge clk);
            in_valid = 1'b1;
            in_re = 16'sd100;
            in_im = -16'sd100;
            in_last = (line == 9);
            @(posedge clk);
            while (!in_ready)
                @(posedge clk);
        end
        @(negedge clk);
        in_valid = 1'b0;
        in_last = 1'b0;
        @(posedge clk);
        if (!frame_error) begin
            $display("FAIL misplaced in_last did not set frame_error");
            errors = errors + 1;
        end

        if (errors == 0) begin
            $display("PASS: ofdm_cfo_corrector matched the fixed-point model on %0d streams, %0d samples; misplaced in_last flagged",
                     streams_done, checked);
            $finish;
        end else begin
            $display("FAIL tb_ofdm_cfo_corrector errors=%0d", errors);
            $fatal(1);
        end
    end
endmodule
