`timescale 1ns/1ps

// Bit-exact check of ofdm_channel_equalizer.v against
// verification/vectors/block08_ofdm_channel_eq_vectors.txt (generated by
// tools/generate_ofdm_channel_eq_vectors.py from the fixed-point model).
// The block is reset before every frame; bins enter with random gaps and the
// output sees random backpressure. Every data bin must match in value, index
// and order; the training symbol must produce no output; the saturation count
// must equal the model's.
module tb_ofdm_channel_equalizer;
    // NORMALIZE=1 checks the zero-forcing mode (CORDIC 1/|G|^2) against its own vectors.
    parameter integer NORMALIZE = 0;
    // Two names, chosen with if: a ?: between strings of different lengths
    // pads the shorter one with NUL characters.
    localparam VECTORS_PLAIN = "verification/vectors/block08_ofdm_channel_eq_vectors.txt";
    localparam VECTORS_NORM = "verification/vectors/block08_ofdm_channel_eq_norm_vectors.txt";
    localparam integer MAX_LINES = 4096;

    reg clk = 1'b0;
    always #5 clk = ~clk;

    reg resetn = 1'b0;
    reg bin_valid = 1'b0;
    wire bin_ready;
    reg signed [15:0] bin_re = 16'sd0;
    reg signed [15:0] bin_im = 16'sd0;
    reg [5:0] bin_index = 6'd0;
    reg bin_last = 1'b0;

    wire out_valid;
    reg out_ready = 1'b1;
    wire signed [15:0] out_re;
    wire signed [15:0] out_im;
    wire [5:0] out_index;
    wire out_last;
    wire trained;
    wire [15:0] train_count;
    wire [31:0] saturation_count;

    ofdm_channel_equalizer #(.NORMALIZE(NORMALIZE)) dut (
        .clk(clk), .resetn(resetn), .retrain(1'b0),
        .bin_valid(bin_valid), .bin_ready(bin_ready),
        .bin_re(bin_re), .bin_im(bin_im), .bin_index(bin_index), .bin_last(bin_last),
        .out_valid(out_valid), .out_ready(out_ready),
        .out_re(out_re), .out_im(out_im), .out_index(out_index), .out_last(out_last),
        .trained(trained), .train_count(train_count), .saturation_count(saturation_count)
    );

    integer v_frame [0:MAX_LINES-1];
    integer v_sym [0:MAX_LINES-1];
    integer v_bin [0:MAX_LINES-1];
    integer v_yr [0:MAX_LINES-1];
    integer v_yi [0:MAX_LINES-1];
    integer v_zr [0:MAX_LINES-1];
    integer v_zi [0:MAX_LINES-1];
    integer v_sat [0:MAX_LINES-1];
    integer n_lines = 0;

    integer fd, scanned;
    integer f, s, b, yr, yi, zr, zi, sat;
    integer errors = 0;
    integer seed = 32'hCE48;
    integer frame, first, last_line, line, expect_ptr, frame_sat, frames_done, checked;
    integer timeout;

    // Output checker: expect_ptr walks through the data lines of the frame.
    always @(posedge clk) begin
        if (resetn && out_valid && out_ready) begin
            while (expect_ptr < last_line && v_sym[expect_ptr] == 0)
                expect_ptr = expect_ptr + 1;
            if (expect_ptr >= last_line) begin
                $display("FAIL frame %0d: unexpected output bin %0d", frame, out_index);
                errors = errors + 1;
            end else begin
                if (out_index !== v_bin[expect_ptr][5:0] || $signed(out_re) !== v_zr[expect_ptr] ||
                    $signed(out_im) !== v_zi[expect_ptr] || out_last !== (v_bin[expect_ptr] == 63)) begin
                    if (errors < 8)
                        $display("FAIL frame %0d symbol %0d bin %0d: got (%0d,%0d) idx %0d, expected (%0d,%0d)",
                                 frame, v_sym[expect_ptr], v_bin[expect_ptr], out_re, out_im, out_index,
                                 v_zr[expect_ptr], v_zi[expect_ptr]);
                    errors = errors + 1;
                end
                checked = checked + 1;
                expect_ptr = expect_ptr + 1;
            end
        end
    end

    always @(negedge clk)
        out_ready <= ($random(seed) & 3) != 0;

    initial begin
        if (NORMALIZE != 0)
            fd = $fopen(VECTORS_NORM, "r");
        else
            fd = $fopen(VECTORS_PLAIN, "r");
        if (fd == 0) begin
            $display("FAIL cannot open the vector file");
            $fatal(1);
        end
        while (!$feof(fd)) begin
            scanned = $fscanf(fd, "%d %d %d %d %d %d %d %d\n", f, s, b, yr, yi, zr, zi, sat);
            if (scanned == 8) begin
                v_frame[n_lines] = f; v_sym[n_lines] = s; v_bin[n_lines] = b;
                v_yr[n_lines] = yr; v_yi[n_lines] = yi;
                v_zr[n_lines] = zr; v_zi[n_lines] = zi; v_sat[n_lines] = sat;
                n_lines = n_lines + 1;
            end
        end
        $fclose(fd);

        checked = 0;
        frames_done = 0;
        first = 0;
        while (first < n_lines) begin
            frame = v_frame[first];
            last_line = first;
            frame_sat = 0;
            while (last_line < n_lines && v_frame[last_line] == frame) begin
                frame_sat = frame_sat + v_sat[last_line];
                last_line = last_line + 1;
            end
            expect_ptr = first;

            resetn = 1'b0;
            repeat (3) @(posedge clk);
            @(negedge clk);
            resetn = 1'b1;

            for (line = first; line < last_line; line = line + 1) begin
                @(negedge clk);
                while (($random(seed) & 3) == 0) begin
                    bin_valid = 1'b0;
                    @(negedge clk);
                end
                bin_valid = 1'b1;
                bin_re = v_yr[line];
                bin_im = v_yi[line];
                bin_index = v_bin[line];
                bin_last = (v_bin[line] == 63);
                @(posedge clk);
                while (!bin_ready)
                    @(posedge clk);
                if (v_sym[line] == 0 && v_bin[line] == 63 && trained) begin
                    $display("FAIL frame %0d: trained before the training symbol ended", frame);
                    errors = errors + 1;
                end
            end
            @(negedge clk);
            bin_valid = 1'b0;
            timeout = 0;
            while (expect_ptr < last_line && timeout < 4000) begin
                @(posedge clk);
                timeout = timeout + 1;
            end
            repeat (4) @(posedge clk);
            if (expect_ptr != last_line) begin
                $display("FAIL frame %0d: %0d expected outputs missing", frame, last_line - expect_ptr);
                errors = errors + 1;
            end
            if (!trained || train_count != 16'd1) begin
                $display("FAIL frame %0d: trained=%0d train_count=%0d", frame, trained, train_count);
                errors = errors + 1;
            end
            if (saturation_count != frame_sat) begin
                $display("FAIL frame %0d: saturation_count %0d, model %0d", frame, saturation_count, frame_sat);
                errors = errors + 1;
            end
            frames_done = frames_done + 1;
            first = last_line;
        end

        if (errors == 0) begin
            $display("PASS: ofdm_channel_equalizer (NORMALIZE=%0d) matched the fixed-point model on %0d frames, %0d equalized bins, saturation counts included",
                     NORMALIZE, frames_done, checked);
            $finish;
        end else begin
            $display("FAIL tb_ofdm_channel_equalizer errors=%0d", errors);
            $fatal(1);
        end
    end
endmodule
